
spring:
 application:
  name: Config-prod 
eureka:
 instance:
 prefer-ip-address: true
client:
fetch-registry: true
registry-with-eureka: true
service-uri:
 defaultZone: http://localhost:8761/eureka
