spring:
 application:
   name: Config-dev
eureka:
 instance:
  prefer-ip-address: true
client:
 fetch-registry: true
 register-with-eureka: true
 service-uri:
  defualtZone: http://localhost:8761/eureka
 
